import Head from 'next/head';
import { Inter } from 'next/font/google';
import HashtagDogController from '@/components/containers/HashtagDog/HashtagDogContainer';
import { withLayout } from '@/hocs/withLayout';
import SimpleLayout from '@/layouts/SimpleLayout';

const inter = Inter({ subsets: ['latin'] });

const Home = () => {
    return (
        <>
            <Head>
                <title>SociAI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HashtagDogController />
        </>
    );
};

export default withLayout(Home, SimpleLayout);
